driver:
  name: dokken
  privileged: true
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  attributes:
    elasticsearch:
      tarball_purge: true
      notify_restart: true
      config:
        cluster.name: foo
      config_v5:
        cluster.name: foo

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts which

- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
    platform: rhel
    intermediate_instructions:
      - RUN yum install -y net-tools initscripts systemd-sysv which lsof

suites:
  - name: version1package
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        plugins:
          head:
            install_source: mobz/elasticsearch-head
        version: 1.7.3

  - name: version1tarball
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        install_method: tarball
        plugins:
          head:
            install_source: mobz/elasticsearch-head
        version: 1.7.3

  - name: version2package
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        plugins:
          head:
            install_source: mobz/elasticsearch-head
        version: 2.4.3

  - name: version2tarball
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        install_method: tarball
        plugins:
          head:
            install_source: mobz/elasticsearch-head
        version: 2.4.3

  - name: version5package
    driver:
      customize:
        memory: 1280
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        config_v5:
          bootstrap.system_call_filter: false
          bootstrap.memory_lock: false
        plugins:
          x-pack:
            install_source: x-pack -b

  - name: version5tarball
    driver:
      customize:
        memory: 1280
    run_list:
      - recipe[elasticsearch-cluster::default]
      - recipe[elasticsearch-cluster::plugins]
    attributes:
      elasticsearch:
        auto_java_memory: true
        install_method: tarball
        config_v5:
          bootstrap.system_call_filter: false
          bootstrap.memory_lock: false
        plugins:
          x-pack:
            install_source: x-pack -b
